### ISSUE TITLE
collapse animation

### ISSUE THREAD

**Issue by shaunlebron** [joshhead/clblocks#1]
How would you go about doing a collapse animation with your model of generating game states?

**Comment by joshhead** [comment]
Good question. I've thought a little about this but not tried to implement it yet.

Re-rendering is not tied 1:1 with the main game loop, so the field can be redrawn at any time by swapping on the `app-state` atom. The most obvious solution I see is to add a flashing animation in the [main game loop](https://github.com/joshhead/clblocks/blob/db25ef90c5e564f124a20dd2211d6d0c128c98d2/src/cljs/clblocks/runner.cljs#L83) where the redraw is currently triggered. I would need to detect if a line has been cleared (I could check if the score has increased), then generate a new game state where the lines have been removed but not collapsed. Swap to game state with holes, timeout, swap to uncleared state, timeout, swap to game state with holes, timeout, repeat, swap to new collapsed game state and continue.

I might try this later to see how well it works.
